# Generated by Django 2.1 on 2019-01-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0006_auto_20190119_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryimage',
            name='category',
            field=models.CharField(default='spam', max_length=500),
        ),
    ]
