# Generated by Django 2.0.4 on 2019-01-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0008_auto_20190119_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
