# Generated by Django 2.1.5 on 2019-01-19 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0009_worker_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigned',
            name='logs',
            field=models.CharField(default='Going On!', max_length=1000),
        ),
    ]
