# Generated by Django 2.1.5 on 2019-01-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0010_assigned_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryimage',
            name='confidence',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='assigned',
            name='logs',
            field=models.CharField(default='New Request Initiated', max_length=1000),
        ),
    ]
