# Generated by Django 2.1.5 on 2019-01-20 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0011_auto_20190120_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigned',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
