# Generated by Django 2.0.4 on 2019-01-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0002_auto_20180807_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_image', models.FileField(upload_to='x.jpg')),
                ('name', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'query_images',
            },
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
