# Generated by Django 2.1.5 on 2019-01-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0003_auto_20190119_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryimage',
            name='query_image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
