# Generated by Django 2.0.4 on 2019-01-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0004_auto_20190119_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryimage',
            name='lat',
            field=models.CharField(default='o', max_length=500),
        ),
        migrations.AddField(
            model_name='queryimage',
            name='long',
            field=models.CharField(default='o', max_length=500),
        ),
    ]
